version: '3'
services:
  docker-mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "9000:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/demo?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - docker-mysql